services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # ВНУТРИ сети Docker приложение общается с базой по внутреннему порту 5432
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lol_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=lol_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      # СНАРУЖИ (для IDEA) порт 5434, а ВНУТРИ контейнера база всегда на 5432
      - "5434:5432"