
spring.application.name=analyzer

riot.api.key=RGAPI-5133aa0f-db73-43ba-b7c8-8b16ea5a5d5a
gemini.api.key=AIzaSyDABQu0ANFr6z4hmjsHxXXd9C7mqTNVlsw

spring.datasource.url=jdbc:postgresql://localhost:5434/lol_db
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect