
spring.application.name=analyzer

riot.api.key=RGAPI-5e64f9c1-4c7f-4b00-a8bc-c2169cb05b49

spring.datasource.url=jdbc:postgresql://localhost:5434/lol_db
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect