
spring.application.name=analyzer

riot.api.key=RGAPI-6fbe528d-4900-44f1-9e1a-512e0f7680ea

spring.datasource.url=jdbc:postgresql://localhost:5434/lol_db
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect